### ISSUE TITLE
Searching for subfolder does not work

### ISSUE THREAD

**Issue by ayyilmaz** [godofredoninja/simply#85] opened 2021-02-26 16:28 UTC
My blog hosted on `mydomain.com/blog/` but search function shows link of post as `mydomain.com/title/`.

It should be `mydomain.com/blog/title/`

**Comment by godofredoninja** [comment] 2021-02-26 16:47
They can inspect the link that is coming out in the search engine.
and the inspected code you send me.

**Comment by godofredoninja** [comment] 2021-02-26 17:24
The problem is that I am using the `slug` to not overload the `json` file.

I will give you two possible solutions.

1. if all your urls are based on.

`mydomain.com/blog/slug/` not `mydomain.com/blog/sub/sub/sub/title/`

In this way you will avoid overloading your json file.

```html
<script>
 var searchSettings = {
        key: 'YOUR_API',
        url: 'https://domain.com',
        template: function (result) {
            return '<a href="https://mydomain.com/blog/' + result.slug + '" class="block py-2 pr-3 pl-10"><svg class="icon icon--search" style="margin-left:-28px"><use xlink:href="#icon-search"></use></svg> ' + result.title + '</a>';
        },
    };
</script>
```

---

This option is when you have many different collections. different sub directories. in this case, you have to tell the ghost that you want the URL and not the SLUG.

```html
<script>
var searchSettings = {
        key: 'YOUR_API',
        url: 'https://domain.com',
        api: {parameters: {fields: ['title', 'url']}},
        template: function (result) {
            return '<a href="' + result.url + '" class="block py-2 pr-3 pl-10"><svg class="icon icon--search" style="margin-left:-28px"><use xlink:href="#icon-search"></use></svg> ' + result.title + '</a>';
        },
    };
</script>
```

**Comment by ayyilmaz** [comment] 2021-02-26 18:03
Thank you very much, both of them is working. I have used first option.

**Comment by godofredoninja** [comment] 2021-02-27 02:07
If everything is fixed. Can you close this issue?

**Closed** 2021-03-01 17:26 UTC
